use QRandomGenerator instead of the deprecated KRandomSequence
This was to fix the following compilation issue on kde
framework 5.75.0:

ImageData.h:84:3: error: 'KRandomSequence' does not name a type
   84 |   KRandomSequence random;
      |   ^~~~~~~~~~~~~~~

Signed-off-by: Joshua Houghton <joshua.houghton@yandex.ru>